#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-chains-info.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _set */
const
  _set =
    _libcrash._set;

const
  _libevm_chains_info =
    await import(
      "./libevm-chains-info");
/* global
     _evm_chains_db_path_get */
const
  _evm_chains_db_path_get =
    _libevm_chains_info._evm_chains_db_path_get;
/* global
     _evm_chains_info_get */
const
  _evm_chain_info_get =
    _libevm_chains_info._evm_chain_info_get;
/* global
     _rpc_backends_get */
const
  _rpc_backend_get =
    _libevm_chains_info._rpc_backend_get;
/* global
     _evm_chains_info */
const
  _evm_chains_info =
    _libevm_chains_info._evm_chains_info;
/* global
     _db_paths_auto_detect */
const
  _db_paths_auto_detect =
    _libevm_chains_info._db_paths_auto_detect;
/* global
     _db_types_auto_detect */
const
  _db_types_auto_detect =
    _libevm_chains_info._db_types_auto_detect;
/* global
     _input_type_auto_detect */
const
  _input_type_auto_detect =
    _libevm_chains_info._input_type_auto_detect;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "evm-chains-info.js");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       runtime_environment:
         writable */
  _set(
    "runtime",
    "environment",
    "");
  /* global
       call_date:
         writable */
  _set(
    "call",
    "date",
    "");
  /* global
       target_command:
         writable */
  _set(
    "target",
    "command",
    "");
  /* global
       input_type:
         writable */
  _set(
    "input",
    "type",
    "");
  /* global
       output_type:
         writable */
  _set(
    "output",
    "type",
    "");
  /* global
       retrieval_mode:
         writable */
  _set(
    "retrieval",
    "mode",
    "");
  /* global
       db_types:
         writable */
  _set(
    "retrieval",
    "mode",
    []);
  /* global
       user_level:
         writable */
  _set(
    "user",
    "level",
    "");
  /* global
       db_paths:
         writable */
  _set(
    "db",
    "paths",
    []);
  /* global
       selection_method:
         writable */
  _set(
    "selection",
    "method",
    "");
  /* global
       api_key:
         writable */
  _set(
    "api",
    "key",
    "");
  /* global
       target_chain:
         writable */
  _set(
    "target",
    "chain",
    "");
  /* global
       networks_all:
         writable */
  _set(
    "networks",
    "all",
    "");
  /* global
       quiet:
         writable */
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
  /* global
       verbose:
         writable */
  _global[
    "verbose"] =
    "";
}

function 
  _overrides_set() {
  _override_set(
    "call",
    "date",
    _get_date_human());
  _override_set(
    "target",
    "command",
    "get");
  _input_type_auto_detect();
  _override_set(
    "output",
    "type",
    "name");
  _override_set(
    "retrieval",
    "mode",
    "offline");
  _override_set(
    "selection",
    "method",
    "kirsh");
  _override_set(
    "api",
    "key",
    "n");
  _override_set(
    "user",
    "level",
    "y");
  _override_set(
    "networks",
    "all",
    "n");
  _db_paths_auto_detect(
    target_chain,
    user_level);
  _db_types_auto_detect();
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `                Call date:   ${call_date}`,
      `      Runtime environment:   ${runtime_environment}`,
      `           Target command:   ${target_command}`,
      `               Input type:   ${input_type}`,
      `              Output type:   ${output_type}`,
      `           Retrieval mode:   ${retrieval_mode}`,
      `           Database types:   ${db_types}`,
      `      User-level database:   ${user_level}`,
      `                  API key:   ${api_key}`,
      `     RPC selection method:   ${selection_method}`,
      `             All networks:   ${networks_all}`,
      `             Target chain:   ${target_chain}`,
      `           Database paths:   ${db_paths}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "Returns info about EVM blockchains.",
      "",
      "Usage:",
      "",
      "  evm-chains-info.js",
      "    [options]",
      "    <target-chain>",
      "",
      "  options:",
      "",
      "     -C --command                    Target command. Can be 'get' or 'set'",
      "                                     or 'check'.",
      `       <target-command>              Default: '${target_command}`,
      "",
      "     -i --input-type                 Input type. It can be 'id' or 'name'.",
      `       <input-type>                  Default: '${input_type}'`,
      "",
      "     -o --output-type                Output type. It can be 'id', 'name',",
      "       <output-type>                 'rpc', 'explorers'.",
      `                                     Default: '${output_type}'`,
      "",
      "     -m --retrieval-mode             It can be 'offline'.",
      `       <retrieval-mode>              Default: '${retrieval_mode}'`,
      "",
      "     -t --db-type                    It can be 'node', 'system'.",
      `       <db-type>                     Default: '${retrieval_mode}'`,
      "",
      "     -u --user-level                 It can be 'y' or 'n'.",
      `       <user-level>                  Default: '${user_level}'`,
      "",
      "     -d --db-path                    Path of the chains' info json file",
      "       <db-path>                     to be used for 'offline' retrieval.",
      `                                     Default: '${db_paths}'`,
      "",
      "     -s --selection-method           When output type is 'rpc',",
      "       <selection-method>            selection criterion to use when",
      "                                     more than one is available.",
      "                                     It can be 'kirsh', 'random' or 'all'.",
      `                                     Default: '${selection_method}'`,
      "",
      "     -k                              If selected, when output type is 'rpc',",
      "                                     includes the ones requiring an API key.",
      `                                     Default: '${api_key}'`,
      "     -a --all                        Whether to show results for all networks.",
      `                                     Default: '${networks_all}'`,
      "",
      "     -h --help                       This message.",
      "     -v --verbose                    Enable verbose output."
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  const
    _argv_args = {
      "booleans": [
        "h",
        "help",
        "v",
        "verbose"
      ]
    };
  const
    _argv =
      await _argv_get(
        _argv_args);
  const
    _global =
      _global_get();
  const
    _options =
      _argv[
        "_"];
  _global[
    "quiet"] = 
    "y";
  _help_display =
    false;
  _set(
    "runtime",
    "environment",
    "node");
  if ( _argv["h"] == true ) {
    _help_display =
      true;
  }
  if ( _argv["help"] == true ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    _global[
      "quiet"] =
      "n";
    _overrides_set();
    _usage(
      0);
  }
  if ( typeof(
         _argv) == "undefined" ||
       _argv[
         "_"].length < 1 &&
       _help_display == false ) {
    _msg =
      "Target chain argument required.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  else if ( _help_display == true ) {
    _usage(
      0);
  }
  _set(
    "target",
    "chain",
    _argv[
      "_"][
        0]);
  if ( "C" in _argv ) {
    _set(
      "target",
      "chain",
      _argv[
        "C"]);
  }
  if ( "command" in _argv ) {
    _set(
      "target",
      "command",
      _argv[
        "command"]);
  }
  if ( "i" in _argv ) {
    _set(
      "input",
      "type",
      _argv[
        "i"]);
  }
  if ( "input-type" in _argv ) {
    _set(
      "input",
      "type",
      _argv[
        "input-type"]);
  }
  if ( "o" in _argv ) {
    _set(
      "output",
      "type",
      _argv[
        "o"]);
  }
  if ( "output-type" in _argv ) {
    _set(
      "output",
      "type",
      _argv[
        "output-type"]);
  }
  if ( "m" in _argv ) {
    _set(
      "retrieval",
      "mode",
      _argv[
        "m"]);
  }
  if ( "retrieval-mode" in _argv ) {
    _set(
      "retrieval",
      "mode",
      _argv[
        "retrieval-mode"]);
  }
  if ( "u" in _argv ) {
    _set(
      "user",
      "level",
      _argv[
        "u"]);
  }
  if ( "user-level" in _argv ) {
    _set(
      "user",
      "level",
      _argv[
        "user-level"]);
  }
  const
    _db_paths =
      _get(
        "db",
        "paths");
  if ( "d" in _argv ) {
    _db_paths.push(
      _argv[
        "d"]);
  }
  if ( "db-path" in _argv ) {
    _db_paths.push(
      _argv[
        "db-paths"]);
  }
  _set(
    "db",
    "paths",
    _db_paths);
  const
    _db_types =
      _get(
        "db",
        "types");
  if ( "t" in _argv ) {
    _db_types.push(
      _argv[
        "t"]);
  }
  if ( "db-types" in _argv ) {
    _db_types.push(
      _argv[
        "db-types"]);
  }
  _set(
    "db",
    "types",
    _db_types);
  if ( "s" in _argv ) {
    _set(
      "selection",
      "method",
      _argv[
        "s"]);
  }
  if ( "selection-method" in _argv ) {
    _set(
      "selection",
      "method",
      _argv[
        "selection-method"]);
  }
  if ( "k" in _argv ) {
    _set(
      "api",
      "key",
      "y");
  }
  if ( "api-key" in _argv ) {
    _set(
      "api",
      "key",
      "y");
  }
  if ( "a" in _argv ) {
    _set(
      "networks",
      "all",
      "y");
  }
  if ( "networks-all" in _argv ) {
    _set(
      "networks",
      "all",
      "y");
  }
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"]) {
    _global[
      "verbose"] =
      true;
  }
  if ( _global[
         "verbose"] ) {
    _global[
      "quiet"] =
      "n";
  }
}

function
  _url_parse() {
  runtime_environment =
    "browser";
  target_chain =
    _argv_url_get(
      "chain")[
        0];
  target_command =
    _argv_url_get(
      "command")[
        0];
  input_type =
    _argv_url_get(
      "input_type")[
        0];
  output_type =
    _argv_url_get(
      "output_type")[
        0];
  input_type =
    _argv_url_get(
      "input_type")[
        0];
  retrieval_mode =
    _argv_url_get(
      "retrieval_mode")[
        0];
  user_level =
    _argv_url_get(
      "user_level")[
        0];
  db_paths.push(
    _argv_url_get(
      "db_path")[
        0]);
  selection_method =
    _argv_url_get(
      "selection_method")[
        0];
  api_key =
    _argv_url_get(
      "api_key")[
        0];
  networks_all =
    _argv_url_get(
      "networks_all")[
        0];
  quiet =
    _argv_url_get(
      "quiet");
  if ( quiet.length === 0 ) {
    quiet =
      "n";
  }
}

async function
  _evm_chains_info_cmdline(
    _app_opts) {
  let
    _result,
    _results;
  _results =
    await _evm_chains_info.apply(
      null,
      _app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "undefined"  ) {
    const
      _msg =
        `No results!`;
    _msg_error(
      _msg,
      1);
  }
  const
    _results_length =
      _results.length;
  const
    _results_length_type =
      typeof(
        _results_length);
  if ( _results_length_type == "undefined" ) {
    _results =
      Object.keys(
        _results);
  }
  for ( _result of _results ) {
    _echo(
      _result);
  }
  _exit(
    0);
}

_global_variables();
if ( await _cmdline_check(
       "evm-chains-info.js") ||
     await _cmdline_check(
       "evm-chains-info") ) {
  await _cmdline_parse();
}
else{
  _url_parse();
}
await _overrides_set();
_config_show();
app_opts = [
  target_command,
  input_type,
  output_type,
  retrieval_mode,
  db_types,
  selection_method,
  api_key,
  networks_all,
  target_chain,
  db_paths,
  user_level
];
await _evm_chains_info_cmdline(
  app_opts);
