#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-chains-info
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* global 
     db_paths */
/* global
     user_level */

const
  _libcrash_module =
    require(
      "crash-js");
/* global
     _homedir_get */
/* eslint-disable-next-line
     no-global-assign */
_homedir_get =
  _libcrash_module._homedir_get;
/* global
     _file_exists */
/* eslint-disable-next-line
     no-global-assign */
_file_exists =
  _libcrash_module._file_exists;
/* global
     _json_read */
/* eslint-disable-next-line
     no-global-assign */
_json_read =
  _libcrash_module._json_read;
/* global
     _msg_info */
/* eslint-disable-next-line
     no-global-assign */
_msg_info =
  _libcrash_module._msg_info;
/* global
     _msg_error */
/* eslint-disable-next-line
     no-global-assign */
_msg_error =
  _libcrash_module._msg_error;
/* global
     _path_join */
/* eslint-disable-next-line
     no-global-assign */
_path_join =
  _libcrash_module._path_join;

const
  _ethereum_data_module =
    require(
      "ethereum-data");
/* global
     _data_get */
/* eslint-disable-next-line
     no-global-assign */
const
  _data_get =
    _ethereum_data_module._data_get;

function
  _evm_chains_db_path_get(
    _user,
    _chain_id,
    _format) {
  let
    _db_exists,
    _db_name,
    _path;
  if ( typeof(
         _user) == "undefined" ) {
    _user =
      false;
  }
  if ( typeof(
         _chain_id) == "undefined" ) {
    _chain_id =
      "";
  }
  if ( typeof(
         _format) == "undefined" ) {
    if ( _chain_id != "" ) {
      _format =
        "split";
    }
    else if ( _chain_id == "" ) {
    _format =
      "unified";
    }
  }
  if ( _format == "unified" ) {
    _db_name =
      "chains.json";
  }
  else if ( _format == "split" ) {
    _db_name =
      `${_chain_id}.json`;
  }
  if ( _user == true ) {
    _path =
      _path_join(
        [_homedir_get(),
         ".config",
         "evm-chains",
         _db_name]);
    const
      _db_exists =
        _file_exists(
          _db_path);
    if ( _db_exists == false ) {
      _user =
        false;
    }
  }
  if ( _user == false ) {
    _path =
      _path_join(
        [process.env.NODE_PATH,
         "..",
         "evm-chains",
         "chains.json"]);
  }
  else {
    _msg_error(
      "Input variable '_user' must be a boolean",
      0);
  }
  return _path;
}

function
  _evm_chain_info_get(
    _chain_id,
    _chain_info,
    _db_path) {
  let
    _data,
    _db;
  if ( typeof(
         _db_path) == "undefined" ) {
    _db_path =
      _evm_chains_db_path_get(
        false);
  }
  const
    _db_exists =
      _file_exists(
        _db_path);
  if ( _db_exists == false ) {
    if ( typeof window === 'undefined' &&
         ( typeof global !== 'undefined' && global.global === global ) &&
         typeof __webpack_require__ !== 'function' ) {
      _data =
        _data_get(
          _chain_id);
      _msg =
        `Displaying data for ` +
        `chain '${_chain_id}'.`;
      _msg_info(
        _msg);
      console.log(
        _data);
    }
    // _msg_error(
    //   "Database file does not exists.",
    //   1);
  }
  _db =
    _json_read(
      _db_path);
  for ( _chain_info of _db) {
    if ( _chain_info["chainId"] == _chain_id ) {
      return _chain_info;
    }
  }
  _msg_error(
    `Network '${_chain_id}' not found.`,
    1);
}

function
  _rpc_backend_get(
    _network_chain_id,
    _selection_method,
    _db_path) {
  let
    _chain_id,
    _chain_info;
  if ( _network_chain_id == undefined ) {
    _msg_error(
      "Network's ChainID not specified.",
      1);
  }
  if ( _selection_method == undefined ) {
    _selection_method =
      "kirsh";
  }
  if ( _db_path == undefined ) {
    _db_path =
      _evm_chains_db_path_get(
        false);
  }
  _chain_id =
    Number(
      _network_chain_id);
  _chain_info =
    _evm_chain_info_get(
      _chain_id,
      _db_path);
  if ( _selection_method == "kirsh" ) {
    return _chain_info["rpc"][0];
  }
  else {
    _msg_error(
      "Unknown selection method.",
      1);
  }
}

function _rpc_backends_get(
    _networks_chain_ids,
    _selection_method,
    _db_path) {
    let
      _chain_id,
      _rpc_backend_get_opts,
      _rpcs;
  if ( _selection_method == undefined ) {
    _selection_method =
      "kirsh";
  }
  if ( _db_path == undefined ) {
    _db_path =
      _evm_chains_db_path_get(
        false);
  }
  _rpcs =
    [];
  for ( _chain_id of _networks_chain_ids ) {
    _rpc_backend_get_opts = [
      _chain_id,
      _selection_method,
      _db_path
    ];
    _rpc_backend =
      _rpc_backend_get.apply(
        null,
        _rpc_backend_get_opts);
    _rpcs.append(
      _rpc_backend);
  }
  return _rpcs;
}

function
  _db_path_check(
    _db_path) {
  if ( ! _file_exists(
       _db_path) ) {
    const
      _msg =
        `Database at ` +
        `'${_db_path}' does not exist.`;
    _msg_error(
      _msg,
      1);
  }
}

function
  _db_get(
    _db_path,
    _input_type,
    _output_type,
    _selection_method,
    _api_key,
    _target_chain) {
  let
    _filter,
    _filter_key,
    _filter_output_type,
    _result,
    _rpcs,
    _msg;
  _filter_output_type =
    _output_type;
  if ( _input_type == "id" ) {
    _filter_key =
      "chainId";
    _filter_key =
      _target_chain;
  }
  else if ( _input_type == "testnet" ) {
    _msg =
      "Like I have to agg a tag.";
    _msg_info(
      _msg);
  }
  if ( _output_type == "id"  ) {
    _filter_output_type =
      "chainId";
  }
  if ( _networks_all == "y" ) {
    _filter =
      _all_get(
        _filter_output_type);
  }
  else if ( _networks_all == "n" ) {
    // this doesnt work the same in
    // javascript as in bash i suppose.
    // _filter =
    //   _filter_get(
    //     _filter_key,
    //     _filter_value,
    //     _filter_output_type);
    _db =
      _json_read(
        _db_path);
  }
}

function
  _input_type_auto_detect() {
  if ( input_type == "" ) {
    if ( isNaN(target_chain) ) {
      input_type =
        "name";
    }
    else {
      input_type =
        "id";
    }
  }
}

function
  _db_path_auto_detect() {
  let
    _chains,
    _type_primary,
    _type_fallback,
    _msg;
  if ( user_level == "y" ) {
    _type_primary =
      "user";
    _type_fallback =
      "system";
  }
  else if ( user_level == "n" ) {
    _type_primary =
      "system";
    _type_fallback =
      "user";
  }
  const
    _db =
      _evm_chains_db_path_get(
        _type_primary,
        "",
        "unified");
  const
    _db_split =
      _evm_chains_db_path_get(
        _type_primary,
        _chain_id,
        "split");
  const
    _db_fallback =
      _db_default_path_get(
        _type_fallback,
        "",
        "unified");
  const
    _db_fallback_split =
      _db_default_path_get(
        _type_fallback,
        "split");
  if ( _file_exists(
           _db_split) ) {
    db_paths.push(
      _db_split);
  }
  else {
    _msg =
      `Default per-network database ` +
      `'${_db_split}' ` +
      `not found, trying '${_db}'.`;
    _msg_info(
      _msg);
  }
  if ( _file_exists(
         _db) ) {
    db_paths.push(
      _db);
  }
  else {
    _msg =
      `Default unified database ` +
      `'${_db_split}' ` +
      `not found, trying '${_db}'.`;
    _msg_info(
      _msg);
  }
  if ( _file_exists(
           _db_fallback_split) ) {
    db_paths.push(
      _db_fallback_split);
  }
  else {
    _msg =
      `Fallback per-network database ` +
      `'${_db_fallback_split}' ` +
      `not found, trying '${_db_fallback}'.`;
    _msg_info(
      _msg);
  }
  if ( _file_exists(
         _db_fallback) ) {
    db_paths.push(
      _db_fallback);
  }
  else {
    _msg =
      `Fallback database ` +
      `'${_db_fallback_split}' ` +
      `not found too!`;
    _msg_error(
      _msg,
      1);
  }
}

function
  _evm_chains_info_get(
    _retrieval_mode,
    _input_type,
    _selection_method,
    _db_paths) {
  let
    _db,
    _db_path,
    _msg,
    _networks_total,
    _results;
  _networks_total =
    0;
  if ( _retrieval_mode == "offline" ) {
    for ( _db_path of _db_paths ) {
      _msg =
        `Looking in '${_db_path}'.`;
      _msg_info(
        _msg);
      _db_path_check(
        _db_path);
      if ( _input_type != "amount" ) {
        _db_get(
	  _db_path,
          _input_type,
          _output_type,
          _selection_method,
          _api_key,
          _target_chain);
      }
      else if ( _input_type == "amount" ) {
        _db =
          _json_read(
            _db_path);
	_networks_total =
          _db.length;
      }
    }
    if ( _input_type != "amount" ) {
      if ( _results.length == 0 ) {
        _msg =
          `No results found for network ` +
          `'${_target_chain}'.`;
        _msg_error(
          _msg,
          0);
      }
      for ( _result of _results ) {
        console.log(
          _result);
        if ( _selection_method != "all" ) {
          break;
        }
      }
    }
    else if ( _input_type == "amount" ) {
      console.log(
        _networks_total);
    }
  }
  else if ( _retrieval_mode == "online" ) {
    _msg =
      `About to implement it probably.`;
    _msg_error(
      _msg,
      1);
  }
}

function
  _evm_chains_info_set(
    _input_type) {
  if ( _input_type == "id" ) {
    console.log(
      _input_type);
  }
}

function
  _evm_chains_info(
    _target_command,
    _input_type,
    _output_type,
    _retrieval_mode,
    _selection_method,
    _api_key,
    _networks_all,
    _target_chain,
    _db_paths) {
  if ( _target_command == "get" ) {
    _evm_chains_info_get(
      _target_chain,
      _retrieval_mode,
      _input_type,
      _selection_method,
      _db_paths);
  }
  else if ( _target_command == "set" ) {
    _evm_chains_info_set(
      _input_type);
  }
  else {
    const
      _msg =
        `Unknown command ` +
        `'${_target_command}'.`;
    _msg_error(
      _msg,
      1);
  }
}

module.exports = {
  _db_path_auto_detect:
    _db_path_auto_detect,
  _evm_chains_db_path_get:
    _evm_chains_db_path_get,
  _evm_chains_info:
    _evm_chains_info,
  _evm_chains_info_get:
    _evm_chains_info_get,
  _evm_chains_info_set:
    _evm_chains_info_set,
  _input_type_auto_detect:
    _input_type_auto_detect,
  _rpc_backend_get:
    _rpc_backend_get,
  _rpc_backends_get:
    _rpc_backends_get
}
